tags:
  [
    {
      frame: "tag_156",
      id: 156,
      corners: [
        [-0.053,0.053,0.0],
        [0.053,0.053,0.0],
        [0.053,-0.053,0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
